name: Automated Unit Testing

on: 
  push:
    branches:
      - main
      - workflow 
  pull_request:
    branches:
      - main
      - workflow  
  workflow_dispatch:

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test
